quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=\ 
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/randomplace

quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true

quarkus.rest-client.country-api.url=https://api.3geonames.org
quarkus.rest-client.elevation-api.url=https://api.open-meteo.com